#
# <%= appNameSlug %>
# https://github.com/<%= userName %>/<%= appNameSlug %>
#
# Copyright (c) <%= currentYear %>, <%= authorName %>
# Licensed under the <%= license %> license.
#

test:
	@NODE_ENV=test ./node_modules/mocha/bin/mocha -G -R spec -u bdd -t 6000 --globals chai --colors

.PHONY: test